if(system.file(package = "pacman") == ""){
  install.packages("pacman")
}

pacman::p_load(
  finetune,
  doParallel,
  data.table,
  tidymodels,
  conflicted,
  tidyverse,
  targets,
  tarchetypes,
  here,
  readxl,
  janitor,
  googledrive,
  themis,
  textrecipes,
  tidypredict,
  finetune,
  fst,
  stopwords,
  textstem,
  fastDummies
)
conflicts_prefer(dplyr::select)
conflicts_prefer(dplyr::filter)
conflicts_prefer(spatstat.geom::area)
conflicts_prefer(dplyr::lag)
conflicts_prefer(yardstick::spec)
